# Generated by Django 4.0.2 on 2022-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=8, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
